export const BrightSpacePage = {
    url: '',
    'Username Input': '#userName',
    'Password Input': '#password',
    'Brightspace AQA course link':
        '.d2l-my-courses-widget.d2l-token-receiver |shadow| d2l-my-courses-legacy |shadow| d2l-my-courses-content-animated |shadow| div.my-courses-content > d2l-course-tile-grid |shadow| div > div > d2l-course-tile |shadow| div > a > div[class="course-info"] > div[class="course-text"][text*="Brightspace [AQA Course]"]',
    //[text*= "Brightspace [AQA Course]"]',
    'Sign In Button': '//button[text()="Log In"]',

    // 'Brightspace AQA course link':
    //     '.d2l-my-courses-widget.d2l-token-receiver |shadow| d2l-my-courses-legacy |shadow| d2l-my-courses-content-animated |shadow| div.my-courses-content > d2l-course-tile-grid |shadow| div > div:nth-of-type(2) > d2l-course-tile |shadow| div.course-text',
    'Quizzes tab': "//div//a[contains(text(), 'Quizzes')]",
    'Content tab': '//div//a[contains(text(), "Content")]',
    'New Quiz button': "//li//button[contains(text(), 'New Quiz')]",
    'Quiz Name': "//*[@id='z_j']",
    'Quiz Restrictions tab': "//a//span[contains(text(), 'Restrictions')]",
    'Quiz Password Input': '//*[@id="z_br"]',
    'Quiz Time Limit': "//label[contains(.,'Recommended Time Limit')]",
    'Recommended time limit in minutes': "//*[@id='z_ch']",
    'Quiz Properties tab': "//a//span[contains(text(), 'Properties')]",
    'Proctoru toggle':
        "//*[@id='toggle_container']/div/div[1]/div[2]/div/label",
    'Brightspace Quiz link': "//a[contains(text(), 'AQA Staging 4 Passing')]",
    'Submit Quiz': "//button[contains(text(), 'Submit Quiz')]",
    'Confirmation Submit Quiz': '//button[@id="z_d"]',
    Done: "//button[contains(text(), 'Done')]",
    Continue: "//button[contains(text(), 'Continue')]",
    quizFrame1: "//iframe[@id='ctl_2']",
    quizFrame2: "//frame[@title='Quiz Content']",
    //TODO NEED updated for shadow path
    'Quiz Save button': '//button[@id="z_b"]',
    'Quiz Save and Close button': '//button[@id="z_a_copy"]',
    'Static Auto Exam': '//a[contains(., "Static BS Auto Exam For Student")]',
    'Static Live+ Exam': '//a[contains(., "Static BS Live+ Exam For Student")]',
    'Static Auto Exam Medium Preset': '//a[contains(., "Medium Preset")]',
    'Test Taker Password': '#z_q',
    'Start Test Button': '#z_a',
    'Answer Radio': '//label[.="True"]/ancestor::tr//input',
    'Progress Quizzes Link':
        '(//div[contains(@class,"datalist")]//span[contains(., "Quizzes")])[last()]',
    'Exams List': '//table//tr',
    'Edit Exam Link': 'a[title="Edit Quiz"]',
    'Description iFrame': '//*[@id="descriptionMessage$html_ifr"]',
    'Description Area': '#tinymce',
    'Course Name Label': '.d2l-navigation-header-left a',
    'Profile Dropdown': '.d2l-navigation-s-personal-menu',
    'Progress Link': '//ul[@class="d2l-list"]//a[.="Progress"]',
    'Static Course Block': '//div[.="BS Static Automation"]',
    'Arrow Link': 'd2l-button-icon',
    'Reports Link': '//d2l-menu/d2l-menu-item[@text="Reports"]',
    'Summary Link': '//d2l-menu/d2l-menu-item[@text="Summary"]',
    'Expand description': '#z_q a',
    'Select Course Button': 'div.d2l-navigation-s-course-menu',
    'BS Static Course':
        '//div[@id="courseSelectorId"]//a[contains(., "BS Static Automation")]',
    'Done Button': '//button[.="Done"]',
};
