export const UserProfilePage = {
    url: '',
    Name: "((//div[@id='profile']//dl[@class='row'])[1]//dd)[1]",
    Username: '#user_username',
    Email: "((//div[@id='profile']//dl[@class='row'])[2]//dd)[1]",
    'First Name': '#user_first_name',
    'Last Name': '#user_last_name',
    Status: "((//div[@id='profile']//dl[@class='row'])[1]//dd)[4]",
    'Role Type': "((//div[@id='profile']//dl[@class='row'])[1]//dd)[5]",
    Address1: "((//div[@id='profile']//dl[@class='row'])[2]//dd)[2]//div[1]",
    Address2: "((//div[@id='profile']//dl[@class='row'])[2]//dd)[2]//div[2]",
    'Mobile Phone': "((//div[@id='profile']//dl[@class='row'])[2]//dd)[4]",
    'User Country': '#user_country',
    'User Street 1': '#user_street1',
    'User City': '#user_city',
    'User Zip': '#user_zip',
    'User State': '#state-select',
    'Time Zone Dropdown': '#user_timezone',
    'Edit User Button':
        '#content > div.container span > a[href^="/users/"][href$="/edit"]',
    'Assign Password Checkbox': '#user_assign_password',
    'Assign Password': '#user_password',
    'Assign Password Confirmation': '#user_password_confirmation',
    'Create User': "//input[@value='Create User']",
    'Confirm User': "//a[contains(@href, 'account_confirmations')]",
    'User Institution': '#s2id_user_institution_id',
};
