export const CommonMoodleRoomsPage = {
    url: '',
    username: '#username',
    password: '#password',
    'Homepage Log In Button': '.btn.btn-primary.snap-login-button',
    'Log in Button': '#loginbtn',
    'Index Log In Button':
        '//div[@id="base-login"]//button[contains(text(), "Log in")]',
    'Browse All Courses': '#snap-pm-trigger',
    'Expand All': '.collapsible-actions a',
    'Home Page AQA Course':
        '(//div[@class="card dashboard-card"]//span[contains(text(), "AQA Course")])[3]',
    'Home Page Static Automation Course':
        '(//div[@class="card dashboard-card"]//span[contains(text(), "Static Automation Course")])[3]',
    'AQA Course':
        '//div[@class="coursename"]//a[contains(text(), "AQA Course")]',
    'Static Automation Course':
        '//div[@class="coursename"]//a[contains(text(), "Static Automation Course")]',
    'Static Automation Exam':
        '//p[contains(., "Automated_Editable")]',
    'Static Automation Exam For Student':
        '//p[.="Static MRooms Automation Test For Student"]/parent::a',
    'Turn Editing On Button':
        '#page-navbar > div.breadcrumb-button > div > form > div > input[type=submit]:nth-child(1)',
    'Create Learning Activity':
        '//button[contains(text(), "Create learning activity")]',
    'Quiz Button': '//a[contains(@title, "Add a new Quiz")]',
    'Quiz Title': '#id_name',
    'Quiz Title Error': '#id_error_name',
    'General Tab': '#id_general .ftoggler a',
    'Timing Accordion Arrow': '#collapseElement-1',
    'Enable Time Limit Checkbox': '#id_timelimit_enabled',
    'Time Limit': '#id_timelimit_number',
    'Time limit error': 'div[data-groupname="timelimit"] fieldset:has(#id_timelimit_number) + div[id="id_error_"]',
    'Require Password': '//i[contains(@title, "Edit password")]',
    'Quiz Password': '#id_quizpassword',
    'Edit Password Pencil': '#id_security i[title="Edit password"]',
    'Open Quiz Checkbox': '#id_timeopen_enabled',
    'Close Quiz Checkbox': '#id_timeclose_enabled',
    'Open Quiz Day': '#id_timeopen_day',
    'Open Quiz Month': '#id_timeopen_month',
    'Open Quiz Year': '#id_timeopen_year',
    'Open Quiz Hour': '#id_timeopen_hour',
    'Open Quiz Minutes': '#id_timeopen_minute',
    'Close Quiz Day': '#id_timeclose_day',
    'Close Quiz Month': '#id_timeclose_month',
    'Close Quiz Year': '#id_timeclose_year',
    'Close Quiz Hour': '#id_timeclose_hour',
    'Close Quiz Minutes': '#id_timeclose_minute',
    'Extra Restrictions Tab': '#id_security .ftoggler a',
    'Timing Tab': '#id_timing .ftoggler a',
    'Edit Settings Link':
        '//div[@id="settingsnav"]//a[contains(text(),"Settings")]',
    'Menu Icon': '#snap-admin-icon',
    'Restore Icon': '//button[contains(text(), "Restore")]',
    'Backup Select None': '#backup-none-included',
    'File Name Input': '#id_setting_root_filename',
    'Perform Backup': '#id_submitbutton',
    'Latest Backup Download': "a[href*='backup-mrooms-latest']",
    'Latest Backup Restore':
        "a[href*='choosebackupfile&filename=backup-mrooms-latest.mbz']",
    'Delete Content & Restore':
        '//label[contains(text(), "Delete the contents of the existing course and then restore")]',
    'Restore AQA List Item':
        '//div[@class="bcs-existing-course backup-section"]//label[contains(text(), "AQA Course")]',
    'Existing Course Continue':
        '//div[@class="bcs-existing-course backup-section"]//input[@value="Continue"]',
    'Next Button': '#id_submitbutton',
    'General Check Icon': '//input[contains(text(), "General")]',
    'Start Exam Button': "//form[contains(@action, 'startattempt')]//button",
    'Continue Button': '//button[contains(text(), "Continue")]',
    'Current Course Continue Button':
        '//div[@class="bcs-current-course backup-section"]//input[@type="submit"]',
    'Submit Button': '#id_submitbutton',
    'Answer Radio': '//input[contains(@id, "answertrue")]',
    'Finish Attempt Button': '//input[@value="Finish attempt ..."]',
    'Submit All Button': '//button[.="Submit all and finish"]',
    'Confirm Submit Button':
        '//div[@class="modal-content"]//button[contains(text(),"Submit all and finish")]',
    'Course Name Label': '#page-mast h1',
    'Description Area': '#id_introeditoreditable',
    'No Password Error': '#id_error_quizpassword',
    'Log In Button': '//a[.="Log in"]',
    'All Exams': 'ul.section li',
    'Exam Link': 'a.mod-link',
    'Edit Quiz Link': '//a[.="Questions"]',
    'Add Dropdown': '#action-menu-toggle-0',
    'Random Question': 'a[data-action=addarandomquestion]',
    'Add Random Question Button': '#id_existingcategory',
    'Toast Message': 'toast-notification > toast-body > toast-content > div > p',
    'Toast Message Button': 'toast-notification > toast-body > toast-content > div > p button',
    'Back to the course': '//button[text()="Back to the course"]',
    'Last Quiz Arrow Button': '(//div[@class="activityinstance"])[last()]//button[@class="snap-edit-asset-more"]',
    'Last Quiz Edit Settings Button': '(//li[contains(@class,"snap-activity")])[last()]//a[contains(@class, "snap-edit-asset")]',
};
